root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-type-checked"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  tsconfigRootDir: {? {path | dirname: ''} : ''}
  project:
    - "./tsconfig.json"
    - "./tsconfig.node.json"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "dist/*"
rules:
  indent:
    - off
    - 4
  quotes:
    - error
    - double
  semi:
    - off
    - always
  no-unused-vars: off
  prefer-const: off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/prefer-as-const": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/no-invalid-this": 2
  no-var: off
